# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Wynn Plaza Condominium
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here.
  Experience life in the heart of the city today.
  At the Wynn Plaza, we've made sure that your unit is ready for occupancy the minute you sign.
  Just a fast and easy way to move in to your new life.
copyright: 'Copyright &copy; 2018 Wynn Plaza. All Rights Reserved.'
credits: 'Enjoy all the convenience of life in Manila with us <a href="https://www.facebook.com/WYNN-PLAZA-1746640468892190/">now</a>. <p>Ready for Occupancy. Units Still Available.</p>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/wynn-plaza
  - title: facebook
    url: https://www.facebook.com/WYNN-PLAZA-1746640468892190/
  - title: google
    url:
