# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Your Awesome Site
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2018 Wynn Plaza. All Rights Reserved.'
credits: 'Enjoy all the convenience of life in Manila with us <a href="https://www.facebook.com/WYNN-PLAZA-1746640468892190/">now</a>. <p>Ready for Occupancy. Units Still Available.</p>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/wynn-plaza
  - title: facebook
    url: https://www.facebook.com/WYNN-PLAZA-1746640468892190/
  - title: linkedin
    url: 
